FROM golang:1.8.1-alpine

ARG APP_VERSION=unkown

ADD . /go/src/github.com/stefanprodan/mgob

WORKDIR /go/src/github.com/stefanprodan/mgob

RUN mkdir -p /dist
RUN go build -ldflags "-X main.version=$APP_VERSION" -o /dist/mgob github.com/stefanprodan/mgob

CMD ["ls"]